services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: fraudwatch

  kestra:
    image: kestra/kestra:latest
    command: server standalone --worker-thread=128 -f ./flows --config /etc/config/application.yaml 
    container_name: kestra
    volumes:
      - kestra-data:/app/storage      
      - /var/run/docker.sock:/var/run/docker.sock      
      - /tmp/kestra-wd:/tmp/kestra-wd      
      - $PWD/application.yaml:/etc/config/application.yaml
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      KESTRA_DATABASE_URL: jdbc:postgresql://postgres:5432/fraudwatch
      KESTRA_DATABASE_USERNAME: user
      KESTRA_DATABASE_PASSWORD: pass
    depends_on:
      - postgres

volumes:
  kestra-data: